# For more information: https://laravel.com/docs/sail
version: "3"
services:
  app:
    build: ./
    volumes:
      - ./:/var/www/app
    ports:
      - 4200:4200
    command: npm run dev
    networks:
      - sail
volumes:
  sailmysql:
    driver: local
  sailminio:
    driver: local

networks:
  default:
    driver: bridge
  sail:
    external: true

